# Generated by Django 3.1.5 on 2021-10-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsevents', '0002_auto_20211001_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
