# Generated by Django 3.1.5 on 2021-10-02 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsevents', '0004_auto_20211001_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticles',
            name='content',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
