# Generated by Django 3.1.5 on 2021-10-02 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsevents', '0005_newsarticles_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsArticles',
            new_name='News',
        ),
    ]
