# Generated by Django 3.2.7 on 2021-10-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('newsevents', '0007_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='static/image/userupload/')),
                ('content', models.CharField(max_length=5000)),
            ],
        ),
    ]
