# Generated by Django 3.2.7 on 2021-10-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsevents', '0008_newsarticles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticles',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newsarticles',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
