# Generated by Django 3.2.7 on 2021-10-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsevents', '0009_auto_20211005_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticles',
            name='image',
            field=models.ImageField(upload_to='static/images/userupload/'),
        ),
    ]
