# Generated by Django 3.1.5 on 2021-10-19 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsevents', '0010_alter_newsarticles_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCarousel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='static/images/userupload/')),
                ('btn1', models.CharField(blank=True, max_length=50, null=True)),
                ('btn2', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
