# Generated by Django 3.1.5 on 2021-10-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsevents', '0011_newscarousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscarousel',
            name='btn1Url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newscarousel',
            name='btn2Url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
