# Generated by Django 3.2.7 on 2021-10-06 21:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('profileimage', models.ImageField(null=True, upload_to='static/images/userupload/userprofileimage')),
                ('role', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
