# Generated by Django 3.2.7 on 2021-10-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20211006_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profileimage',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/userupload/userprofileimage'),
        ),
    ]
