# Generated by Django 3.2.7 on 2021-10-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='personalpage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='privacysettings',
            field=models.CharField(choices=[('PU', 'Public'), ('MO', 'Members Only'), ('PR', 'Private')], default='MO', max_length=15),
        ),
    ]
